---
- name: env variables
  shell: 
    env |cat -n


- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy the file tar"
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: Unarchive a file that is already downloaded
  ansible.builtin.unarchive:
    src:  /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/backend
    remote_src: yes
    
- name: env variables backend
  shell: 
    cat -n /home/ubuntu/backend/.env

- name: "install npm packages"
  become: true
  command: npm install
  args:
    chdir: /home/ubuntu/backend

- name: "build appli"
  become: true
  command: npm run build
  args:
    chdir: /home/ubuntu/backend

- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start