---

- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: "Copy the file tar"
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: Unarchive a file that is already downloaded
  ansible.builtin.unarchive:
    src:  /home/ubuntu/artifact.tar.gz
    dest: /home/ubuntu/backend
    remote_src: yes

- name: "Copy the files"
  become: true
  copy:
    src: ~/project/backend/dist
    dest: /home/ubuntu/backend

- name: Start the Application with PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run start