---

- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src:  ~/project/backend/artifact.tar.gz
    dest: /home/ubuntu/backend
    remote_src: yes

- name: "Copy the files"
  become: true
  copy:
    src: ~/project/backend/dist
    dest: /home/ubuntu/backend

- name: Start the Application with PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- run start